apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: teslaapp
  replicas: 2
  template:
    metadata:
      name: teslaapppod
      labels:
        app: teslaapp
    spec:
      containers:
      - name: mavenappcontainer
        image: princebabs/wfapp
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service 
metadata:
  name: app-svc 
spec: 
  selector: 
    app: mavenapp
  type: NodePort
  ports:
  - targetPort: 8080   
    port: 80
    nodePort: 32700
