---
- hosts: docker
  become: true
  tasks:
    - name: Login in to Docker and Push Image
      command: docker login -u princebabs -p Arsenal04
    
    - name: Push Image to DockerHub
      command: docker push princebabs/tesla
