- hosts: eks
  become: true
  tasks: 
    - name: copy deployment manifest files   
      copy: src=princebabs.yml dest=/home/ubuntu/princebabs.yml    
    - name: deploy the web application 
      shell: kubectl apply -f princebabs.yml 
